language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r sales/requirements.txt
# command to run tests
script:
  - python sales/manage.py test
sudo: required
services:
  - docker
