# Generated by Django 3.1.3 on 2020-11-15 18:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('managesales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='number',
            field=models.PositiveIntegerField(help_text='Enter the quantity purchased'),
        ),
    ]
